### ISSUE TITLE
floyd.yml file!

### ISSUE THREAD

**Issue by whatrocks** [dev-matan-tsuberi/dl#1]
Hi! I saw that you checked in your `floyd.yml` file. That's awesome. I just wanted to make sure that you knew that you can use this to "store" your run commands, including mounting datasets, choosing your environment, etc. Then all you'd have to do is type `floyd run` with the floyd-cli tool.

Here's a guide if that's helpful: [https://docs.floydhub.com/floyd_config/](https://docs.floydhub.com/floyd_config/) 👍

**Comment by dev-matan-tsuberi** [comment]
Thanks! I know that. Though I intend to move to paperspace instead anyway.

**Comment by whatrocks** [comment]
Okay, got it. Any particular reason why? Is it the pricing or the feature-set? Would love to hear why you're moving! Thanks.

**Comment by dev-matan-tsuberi** [comment]
Its definitely the pricing. Floydhub is very convenient and has a very good feature-set tailored to machine learning research (though still have a [few kinks](https://forum.floydhub.com/t/tensorboard-link-gives-a-bad-gateway-on-a-running-job/1047/9)) compared to paperspace. But if I can run the same job twice as long for the same price, that wins out.

**Comment by whatrocks** [comment]
Great. Thanks for the feedback! We'll keep that in mind as we continue to improve the UX and overall FloydHub experience.
